export const STAFFS_LOADING = "STAFFS_LOADING";
export const STAFFS_FAILED = "STAFFS_FAILED";
export const ADD_STAFFS = "ADD_STAFFS";
export const ADD_STAFF = "ADD_STAFF";

export const DPTMS_LOADING = "DPTMS_LOADING";
export const DPTMS_FAILED = "DPTMS_FAILED";
export const ADD_DPTMS = "ADD_DPTMS";

export const STAFFS_IN_DPTM_LOADING = "STAFFS_IN_DPTM_LOADING";
export const STAFFS_IN_DPTM_FAILED = "STAFFS_IN_DPTM_FAILED";
export const ADD_STAFFS_IN_DPTM = "ADD_STAFFS_IN_DPTM";

export const SALARY_LOADING = "SALARY_LOADING";
export const SALARY_FAILED = "SALARY_FAILED";
export const ADD_SALARY = "ADD_SALARY";
